<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/comment.proto

namespace GPBMetadata\Protobuf\Protos;

class Comment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a510a1d70726f746f6275662f70726f746f732f636f6d6d656e742e7072" .
            "6f746f120650726f746f7322200a0455736572120a0a0269641801200128" .
            "09120c0a046e616d65180220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

